# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='phase_days',
        ),
        migrations.RemoveField(
            model_name='period',
            name='phase_hours',
        ),
        migrations.RemoveField(
            model_name='period',
            name='phase_min',
        ),
        migrations.AddField(
            model_name='roundtype',
            name='phase_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundtype',
            name='phase_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundtype',
            name='phase_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
