# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0002_auto_20160810_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
