# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0003_auto_20160816_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundtype',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logrounds.Period'),
        ),
    ]
