# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0004_auto_20160817_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundtype',
            old_name='rt_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='roundtype',
            old_name='rt_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='logdef',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Maximum Bound'),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='high_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Absolute Maximum Bound'),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Minimum Bound'),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='low_low',
            field=models.FloatField(blank=True, null=True, verbose_name='Absolute Minimum Bound'),
        ),
        migrations.AlterField(
            model_name='period',
            name='unit',
            field=models.CharField(help_text='Units for the scale (days, hours, or minutes)', max_length=10),
        ),
    ]
