# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0005_logentry_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdef',
            name='rt',
        ),
        migrations.AddField(
            model_name='logdef',
            name='LogSets',
            field=models.ManyToManyField(to='logrounds.LogSet'),
        ),
    ]
