# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0007_auto_20160629_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdef',
            name='LogSets',
            field=models.ManyToManyField(related_name='columns', to='logrounds.LogSet'),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='selection_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='logrounds.Selection_value_choices'),
        ),
        migrations.AlterField(
            model_name='logset',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row', to='logrounds.RoundType'),
        ),
    ]
