# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0009_auto_20160629_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdef',
            name='LogSets',
        ),
        migrations.AddField(
            model_name='logdef',
            name='rt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='col', to='logrounds.RoundType'),
            preserve_default=False,
        ),
    ]
