# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0010_auto_20160629_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtype',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
