# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0011_roundtype_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='logset',
            name='log_date',
            field=models.DateTimeField(default=datetime.date(2016, 6, 29)),
            preserve_default=False,
        ),
    ]
