# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0013_auto_20160629_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtype',
            name='start_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logset',
            name='log_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
