# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0014_auto_20160630_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdef',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='high_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='low_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdef',
            name='units',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='num_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='select_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection_value_choices',
            name='choice_name',
            field=models.CharField(max_length=24),
        ),
    ]
