# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0016_logentry_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdef',
            name='LogSet',
            field=models.ManyToManyField(through='logrounds.LogEntry', to='logrounds.LogSet'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='LogDef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logrounds.LogDef'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='LogSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logrounds.LogSet'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.TimeField(default=datetime.time(12, 8, 6, 459281)),
        ),
    ]
