# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0017_auto_20160630_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-log_time']},
        ),
        migrations.AddField(
            model_name='logentry',
            name='irregular_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.TimeField(default=datetime.time(13, 32, 28, 289980)),
        ),
    ]
