# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0018_auto_20160630_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdef',
            name='has_qualatative_data',
        ),
        migrations.RemoveField(
            model_name='logdef',
            name='high',
        ),
        migrations.RemoveField(
            model_name='logdef',
            name='high_high',
        ),
        migrations.RemoveField(
            model_name='logdef',
            name='low',
        ),
        migrations.RemoveField(
            model_name='logdef',
            name='low_low',
        ),
        migrations.RemoveField(
            model_name='logdef',
            name='units',
        ),
        migrations.AddField(
            model_name='selection_value_choices',
            name='has_qualatative_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selection_value_choices',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection_value_choices',
            name='high_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection_value_choices',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection_value_choices',
            name='low_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection_value_choices',
            name='units',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.TimeField(default=datetime.time(13, 43, 52, 118108)),
        ),
    ]
