# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0019_auto_20160630_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.TimeField(default=datetime.time(13, 49, 46, 536727)),
        ),
    ]
