# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0022_auto_20160630_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='anachronistic_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logentry',
            name='log_date',
            field=models.DateField(default=datetime.date(2016, 7, 1)),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.TimeField(default=datetime.time(7, 55, 13, 54340)),
        ),
    ]
