# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0023_auto_20160701_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.TimeField(default=datetime.time(12, 10, 11, 394171)),
        ),
        migrations.AlterField(
            model_name='roundtype',
            name='rt_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
