# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0024_auto_20160701_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FlagTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('scale', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={},
        ),
        migrations.RenameField(
            model_name='logdef',
            old_name='LogDef_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='logdef',
            old_name='LogSet',
            new_name='logset',
        ),
        migrations.RenameField(
            model_name='logdef',
            old_name='LogDef_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='LogDef',
            new_name='lg_def',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='LogSet',
            new_name='lg_set',
        ),
        migrations.RemoveField(
            model_name='logdef',
            name='selection_value',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='Entry',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='anachronistic_entry',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='irregular_data',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='log_date',
        ),
        migrations.RemoveField(
            model_name='logset',
            name='log_date',
        ),
        migrations.RemoveField(
            model_name='roundtype',
            name='period',
        ),
        migrations.AddField(
            model_name='logdef',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdef',
            name='high_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdef',
            name='is_qual_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logdef',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdef',
            name='low_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdef',
            name='units',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_edit', to='logrounds.LogEntry'),
        ),
        migrations.AddField(
            model_name='logset',
            name='parent_ls',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='logrounds.LogSet'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.time(10, 39, 2, 52764)),
        ),
        migrations.AlterField(
            model_name='logset',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='logset',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roundtype',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Selection_value_choices',
        ),
        migrations.AddField(
            model_name='flagtypes',
            name='LogEntry',
            field=models.ManyToManyField(through='logrounds.Flags', to='logrounds.LogEntry'),
        ),
        migrations.AddField(
            model_name='flags',
            name='flag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagtype', to='logrounds.FlagTypes'),
        ),
        migrations.AddField(
            model_name='flags',
            name='log_entry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentry', to='logrounds.LogEntry'),
        ),
        migrations.AddField(
            model_name='logdef',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prd', to='logrounds.Period'),
            preserve_default=False,
        ),
    ]
