# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0031_auto_20160705_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 5, 13, 43, 57, 711648)),
        ),
    ]
