# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0034_auto_20160706_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdef',
            name='logset',
        ),
        migrations.AddField(
            model_name='logset',
            name='logdef',
            field=models.ManyToManyField(through='logrounds.LogEntry', to='logrounds.LogDef'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 6, 10, 42, 54, 97369)),
        ),
    ]
