# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0035_auto_20160706_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logset',
            name='logdef',
        ),
        migrations.RemoveField(
            model_name='logset',
            name='parent_ls',
        ),
        migrations.RemoveField(
            model_name='logset',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='lg_set',
        ),
        migrations.AddField(
            model_name='logentry',
            name='next_start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 13, 14, 54, 785161)),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 13, 14, 54, 785104)),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 13, 14, 54, 785438)),
        ),
        migrations.AlterField(
            model_name='period',
            name='phase',
            field=models.CharField(default='0d,0h,0s', help_text='Input in form XXd,XXh,XXs. default 0d,0h,0s', max_length=12),
        ),
        migrations.AlterField(
            model_name='period',
            name='scale',
            field=models.IntegerField(help_text='Time between Sets'),
        ),
        migrations.AlterField(
            model_name='period',
            name='unit',
            field=models.CharField(help_text='Units for the scale (days, hours, or minutes)', max_length=10),
        ),
        migrations.DeleteModel(
            name='LogSet',
        ),
    ]
