# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0036_auto_20160711_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('next_time', models.DateTimeField()),
                ('log_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='next_start_time',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 8, 14, 47, 436222)),
        ),
        migrations.AlterField(
            model_name='period',
            name='phase',
            field=models.CharField(default='0d,0h,0m', help_text='Input in form XXd,XXh,XXm. default 0d,0h,0m', max_length=12),
        ),
        migrations.AddField(
            model_name='logset',
            name='logdef',
            field=models.ManyToManyField(through='logrounds.LogEntry', to='logrounds.LogDef'),
        ),
        migrations.AddField(
            model_name='logset',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row', to='logrounds.RoundType'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='lg_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logrounds.LogSet'),
            preserve_default=False,
        ),
    ]
