# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0038_auto_20160713_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logset',
            name='missed',
        ),
        migrations.AddField(
            model_name='logset',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 12, 10, 44, 220117)),
        ),
    ]
