# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0039_auto_20160713_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 12, 10, 56, 471025)),
        ),
    ]
