# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0040_auto_20160713_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logset',
            name='logdef',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 10, 34, 56, 359916)),
        ),
    ]
