# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0042_auto_20160718_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='phase_days',
        ),
        migrations.RemoveField(
            model_name='period',
            name='phase_hours',
        ),
        migrations.RemoveField(
            model_name='period',
            name='phase_min',
        ),
        migrations.AddField(
            model_name='period',
            name='phase',
            field=models.CharField(default='0d,0h,0m', help_text='Input in form XXd,XXh,XXm. default 0d,0h,0m', max_length=12),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 8, 25, 32, 313528), null=True),
        ),
    ]
