# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0045_auto_20160718_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 10, 54, 12, 984645), null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
