# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0046_auto_20160718_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 12, 37, 25, 292132), null=True),
        ),
    ]
