# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0049_auto_20160719_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flagtypes',
            name='LogEntry',
        ),
        migrations.AlterField(
            model_name='logset',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Missed (Partial)'), (0, 'Missed'), (1, 'In Progress'), (2, 'In Progress (Late)'), (3, 'Complete'), (4, 'Complete (Late)')]),
        ),
    ]
