# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0052_auto_20160720_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdef',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
