# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0053_auto_20160721_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdef',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
