# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0054_auto_20160721_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdef',
            name='period',
        ),
        migrations.AddField(
            model_name='roundtype',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prd', to='logrounds.Period'),
            preserve_default=False,
        ),
    ]
