# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logrounds', '0055_auto_20160728_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundtype',
            name='rt_name',
            field=models.CharField(max_length=50),
        ),
    ]
